### POST gemini test
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyCpjMehH_nOBgO50kcs6fNE_ZGA9IjJI7E
Content-Type:application/json

//body부분
{
  "contents": [{
    "parts":[{"text": "오늘 저녁 메뉴 추천해줘"}]
  }]
}

###